### ISSUE TITLE
no basic auth credentials

### ISSUE THREAD

**Issue by firoz3bits** [LitiumAB/Education#138]
I ran into the following issue while trying to do the steps given in this task.
[Docker Task](https://github.com/LitiumAB/Education/tree/main/Developer%20Education/Tasks/Docker)

I have succesfully completed the task Developer certificate.

I was able to successfully run steps mentioned in [Litium apps](https://docs.litium.com/documentation/litium-apps)

Error message is as follows :

`PS D:\Folder\learn\Litium 8\Tasks\2 - Docker> docker-compose up
[+] Running 0/8
 - elasticsearch Error                                                                                             0.7s
 - direct-payment Error                                                                                            0.7s
 - synonymserver Error                                                                                             0.7s
 - mailhog Error                                                                                                   0.7s
 - direct-shipment Error                                                                                           0.7s
 - sqlserver Pulling                                                                                               0.7s
   - ea362f368469 Pulling fs layer                                                                                 0.0s
   - dc034f624aa1 Pulling fs layer                                                                                 0.0s
   - cafda714f10f Pulling fs layer                                                                                 0.0s
   - c6af4ce68233 Waiting                                                                                          0.0s
   - 2e5e63d166b4 Waiting                                                                                          0.0s
 - kibana Error                                                                                                    0.7s
 - dnsresolver Error                                                                                               0.7s
Error response from daemon: Head "https://registry.litium.cloud/v2/apps/synonym-server/manifests/1.2.0": no basic auth credentials`

**Comment by firoz3bits** [comment]
Found the issue, 

[Litium packages](https://docs.litium.com/documentation/get-started/litium-packages)

I had to run the below command. Missed that.

`docker login registry.litium.cloud -u username`

**Comment by martenw** [comment]
@firoz3bits please let us know if you think there are improvements that we can do in the material.

**Comment by firoz3bits** [comment]
**1. Issue with Litium Nuget feed**
One more issue that I faced was with litium nuget feed.
currently we set nuget feed using the below command:

`dotnet nuget add source https://nuget.litium.com/nuget/ -n Litium -u username -p password`

This stores the password in encrypted form.
So while trying to create a new project after adding dotnet template using 

`dotnet new litmvcacc -test`

The files are not restored succesfully. I ran into an error with litium-db

`dotnet nuget add source https://nuget.litium.com/nuget/ -n Litium -u username -p password --store-password-in-clear-text`

I had to store password in clear text to get over this issue.

**2. Issue with Install a new Accelerator site using the Litium Accelerator template**
This command needs to be updated in Step 3.
`dotnet new litmvcacc -test`  this will throw error.
`dotnet new litmvcacc`  this one works.

**3. Possible update for Dockerfile.**

DockerFile: This could be an issue, I am not sure though.
[Dockerfile](https://github.com/LitiumAB/Education/blob/main/Developer%20Education/Tasks/Installation/Resources/Dockerfile)

`Line 17 FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build` 
When a new file is created from VS 2022
'FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build'


**4. Issues with slieds:** 

slide 36 : link is broken


I will update if I find any other issues.

**Comment by martenw** [comment]
Hi @firoz3bits 

Thank you for your input! 

1. This is covered in #120 and mentioned in Litium docs at https://docs.litium.com/documentation/get-started/litium-packages
2. This is covered in #131 
3. Good input, created #140
4. Good input, created #141

If you notice anything else just create new issues, I might miss if you add additional comments on this closed issue.

/Mårten

**Comment by firoz3bits** [comment]
Sure, I will create new issues,

Thanks for the help.
