### ISSUE TITLE
Slide 145 and React Hooks vs Redux Containers + link

### ISSUE THREAD

**Issue by margr-ateles** [LitiumAB/Education#31]
- The links in slide 145 are stale
- The container/presentational pattern is no longer encouraged as a base, see e.g.
  - https://redux.js.org/style-guide/style-guide#move-complex-logic-outside-components
    > We have traditionally suggested keeping as much logic as possible outside components. That was partly due to encouraging the "container/presentational" pattern [...]
    > ...
    > However, **the use of React hooks does make it somewhat easier to manage logic like data fetching directly inside a component**, and this may replace the need for thunks in some cases.
  - https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0
    > Update from 2019: I wrote this article a long time ago and my views have since evolved. In particular, **I don’t suggest splitting your components like this** anymore. If you find it natural in your codebase, this pattern can be handy. But I’ve seen it enforced without any necessity and with almost dogmatic fervor far too many times. The main reason I found it useful was because it let me separate complex stateful logic from other aspects of the component. Hooks let me do the same thing without an arbitrary division. This text is left intact for historical reasons but don’t take it too seriously.

     (emphasis mine)
     
IMO the solution to this is an update to the accelerator. I realize this is a bigger update.
I personally think hooks are the way to go, but this would require
- a package upgrade of React and ReactDOM to v16.8 (but ofc, just bump to latest at time of upgrade).
- a minor rewrite of the accelerator components
- edit: also a webpack upgrade to v5, because ye olde uglify is not compatible with hooks

**Comment by margr-ateles** [comment]
I guess this issue should move to the forum?

**Comment by martenw** [comment]
@margr-ateles great input, thank you!

* please submit hooks to https://ideas.litium.com/ - it has been discussed but not yet decided if there will be time to include in Litium 8.
* I have passed on your note on containers, if you like you can add this in the idea-portal also as suggested improvement.
* React is being upgraded with Litium 8, possibly also Webpack if there is time.

I will adjust the slide links!

/Mårten

**Comment by margr-ateles** [comment]
I added this: https://ideas.litium.com/ideas/PL-I-201

It contains a rough sketch of the route I'd personally prefer (and where I think the ecosystem is headed, for good reasons imo).

As posted, it's a ball of mud though. It probably needs to go through some form of triage etc, but I personally think there's a cohesive force present there, despite the modules being relatively decoupled, hence the format.

Do what you please with it! 👍 

If you feel there's good reason to create extra items for increased visibility and likeliness of implementation though, I'd be happy to. Just shout out 👍

**Comment by martenw** [comment]
Closing issue.

Broken link is adjusted and the other adjustments are handled in the idea-portal.
