### ISSUE TITLE
Slide 63 - change the use of word "services"

### ISSUE THREAD

**Issue by ganegaar** [LitiumAB/Education#76]
Because Litium is moving towards service oriented architecture, it can be confusing the way following is worded in Slide 63: Component model - Abstractions, in Examples, it says
Example: 
Litium use Services for most functionality and to access and work with entities (BaseProductService, VariantService etc.).

Instead, change to:
Litium uses entities suffixed with "Service" for most functionality and to access and work with entities (BaseProductService, VariantService etc.).

**Comment by martenw** [comment]
![image](https://user-images.githubusercontent.com/1492596/141790841-edf60251-8ec7-4bfe-bfb8-e31ba2761268.png)

**Comment by martenw** [comment]
The term `Service` is used through the application and classes are also decorated as Service:
```C#
[Service(ServiceType = typeof(LoginService), Lifetime = DependencyLifetime.Singleton)]
public abstract class LoginService
```
