### ISSUE TITLE
Slide 83: SalesOrder diagram

### ISSUE THREAD

**Issue by ganegaar** [LitiumAB/Education#78]
It is better to use a UML diagram, Uml for the same diagram as the slide is available in: https://docs.litium.com/documentation/areas/sales/sales-data-modelling

![image](https://user-images.githubusercontent.com/49175064/141402904-0d681941-5a4c-4143-bd0d-154d75cc2c1f.png)

**Comment by martenw** [comment]
![image](https://user-images.githubusercontent.com/1492596/141468718-ef29407d-df98-4d68-9295-2598e214fc20.png)
