### ISSUE TITLE
Slide 84 discounts

### ISSUE THREAD

**Issue by ganegaar** [LitiumAB/Education#79]
To clarify the concept of only having order rows, and separate rows for discounts, use the image below from https://docs.litium.com/documentation/areas/sales/sales-data-modelling/discounts

![image](https://user-images.githubusercontent.com/49175064/141402688-2bb9247c-9d5f-4b95-aa02-2e312a374d0b.png)

**Comment by martenw** [comment]
That is a quite complex image, could we make it simpler like just:

|Articlenumber|Type|Price|
| -- | -- | -- |
|A|Product|300|
|50% off A|Product Discount|-150|
|Grand total||150|

**Comment by martenw** [comment]
![image](https://user-images.githubusercontent.com/1492596/141792142-71cf3e85-c970-4d32-a77d-393b61ff2a49.png)
