### ISSUE TITLE
Slide 122 - Not updated to supported add-ons for Litium 8

### ISSUE THREAD

**Issue by Tasteful** [LitiumAB/Education#84]
![image](https://user-images.githubusercontent.com/357589/141834817-e9ffaeda-6933-45c3-9802-0f281fdc26c4.png)

**Comment by martenw** [comment]
This is described in following Add-On Gotchas slide:
![image](https://user-images.githubusercontent.com/1492596/143432671-109a1eae-a548-41f1-9b1d-2540538f1dd2.png)

All addons will never be available for most recent release.
