### ISSUE TITLE
Author page task

### ISSUE THREAD

**Issue by martenw** [LitiumAB/Education#88]
Path to Administration.resx is wrong

**Comment by Tasteful** [comment]
https://docs.litium.com/documentation/architecture/back-office_1/translations

**Comment by martenw** [comment]
![image](https://user-images.githubusercontent.com/1492596/142015917-77a1fadc-ed19-41ab-b393-1612524af96a.png)
@Tasteful this does not seem to be mentioned on docs

**Comment by Tasteful** [comment]
@martenw What is missing on docs?

**Comment by martenw** [comment]
> @martenw What is missing on docs?

You posted a link that does not mention Administration.resx?

**Comment by Tasteful** [comment]
It describe the `LitiumLocalization` project-element that will make the file a translation file for litium, the name of the file does not matter.

Example you can add
```
<LitiumLocalization Include="Resources\Common*.resx" />
```
or
```
<LitiumLocalization Include="Resources\Administration*.resx" />
```
or
```
<LitiumLocalization Include="Resources\*.resx" />
```
that all will include the resource files that matches the `Include` attribute.
